#!/bin/sh

case $( echo "hybrid\nintel\nnvidia\nback" | dmenu -i -p "Change GPU ?" ) in
	hybrid)
		sudo AnOMR switch hybrid
		;;
	intel)
		sudo AnOMR switch intel
		;;
	nvidia)
		sudo AnOMR switch nvidia
		;;
	back)
		;;
esac
