#!/bin/sh

case $( echo "hybrid\nintel\nnvidia\nback" | dmenu -i -p "Change GPU ?" ) in
	hybrid)
		pkexec AnOMR switch hybrid
		;;
	intel)
		pkexec AnOMR switch intel
		;;
	nvidia)
		pkexec AnOMR switch nvidia
		;;
	back)
		;;
esac
